name: huly
version: "3.8"
services:
  nginx:
    image: "nginx:1.21.3"
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - front

  front:
    image: hardcoreeng/front:v0.6.501
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=8fd5232fc27805cf4899d27789521345e7b2dca04dab315c06fbf73c1a0be031e96c786a52d83222419d02686f53ea8686dd4fa484087544a832855f57e769ed
      - LOVE_ENDPOINT=http://localhost/_love
      - ACCOUNTS_URL=http://localhost/_accounts
      - REKONI_URL=http://localhost/_rekoni
      - CALENDAR_URL=http://localhost/_calendar
      - GMAIL_URL=http://localhost/_gmail
      - TELEGRAM_URL=http://localhost/_telegram
      - STATS_URL=http://localhost/_stats
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=ws://localhost/_collaborator
      - STORAGE_CONFIG=minio|minio?accessKey=ndFN1zncIp0QQewOxm49prynOkZnjXjw&secretKey=SnVpPOO1eWkQuIEGaIARTR4DzmIMOadvHW7iIHHbB1XPwhMV
      - DB_URL=mongodb://lpC3QkyGGvRAmTapCEInN23j:B26ppVvQYhB3MtxrDR040JzidriNbc5J@mongodb:27017/huly?authSource=admin
      - MONGO_URL=mongodb://lpC3QkyGGvRAmTapCEInN23j:B26ppVvQYhB3MtxrDR040JzidriNbc5J@mongodb:27017/huly?authSource=admin
      - TITLE=Huly Self Host
      - DEFAULT_LANGUAGE=en
      - LAST_NAME_FIRST=true
      - DESKTOP_UPDATES_CHANNEL=selfhost

  account:
    image: hardcoreeng/account:v0.6.501
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=8fd5232fc27805cf4899d27789521345e7b2dca04dab315c06fbf73c1a0be031e96c786a52d83222419d02686f53ea8686dd4fa484087544a832855f57e769ed
      - DB_URL=mongodb://lpC3QkyGGvRAmTapCEInN23j:B26ppVvQYhB3MtxrDR040JzidriNbc5J@mongodb:27017/huly?authSource=admin
      - MONGO_URL=mongodb://lpC3QkyGGvRAmTapCEInN23j:B26ppVvQYhB3MtxrDR040JzidriNbc5J@mongodb:27017/huly?authSource=admin
      - TRANSACTOR_URL=ws://transactor:3333;ws://localhost/_transactor
      - STORAGE_CONFIG=minio|minio?accessKey=ndFN1zncIp0QQewOxm49prynOkZnjXjw&secretKey=SnVpPOO1eWkQuIEGaIARTR4DzmIMOadvHW7iIHHbB1XPwhMV
      - FRONT_URL=http://front:8080
      - STATS_URL=http://stats:4900
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://localhost:3000
      - ACCOUNT_PORT=3000

  transactor:
    image: hardcoreeng/transactor:v0.6.501
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=8fd5232fc27805cf4899d27789521345e7b2dca04dab315c06fbf73c1a0be031e96c786a52d83222419d02686f53ea8686dd4fa484087544a832855f57e769ed
      - SERVER_CURSOR_MAXTIMEMS=30000
      - DB_URL=mongodb://lpC3QkyGGvRAmTapCEInN23j:B26ppVvQYhB3MtxrDR040JzidriNbc5J@mongodb:27017/huly?authSource=admin
      - MONGO_URL=mongodb://lpC3QkyGGvRAmTapCEInN23j:B26ppVvQYhB3MtxrDR040JzidriNbc5J@mongodb:27017/huly?authSource=admin
      - STORAGE_CONFIG=minio|minio?accessKey=ndFN1zncIp0QQewOxm49prynOkZnjXjw&secretKey=SnVpPOO1eWkQuIEGaIARTR4DzmIMOadvHW7iIHHbB1XPwhMV
      - FRONT_URL=http://localhost:8087
      - ACCOUNTS_URL=http://account:3000
      - FULLTEXT_URL=http://fulltext:4700
      - STATS_URL=http://stats:4900
      - LAST_NAME_FIRST=true

  collaborator:
    image: hardcoreeng/collaborator:v0.6.501
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=8fd5232fc27805cf4899d27789521345e7b2dca04dab315c06fbf73c1a0be031e96c786a52d83222419d02686f53ea8686dd4fa484087544a832855f57e769ed
      - ACCOUNTS_URL=http://account:3000
      - DB_URL=mongodb://lpC3QkyGGvRAmTapCEInN23j:B26ppVvQYhB3MtxrDR040JzidriNbc5J@mongodb:27017/huly?authSource=admin
      - STATS_URL=http://stats:4900
      - STORAGE_CONFIG=minio|minio?accessKey=ndFN1zncIp0QQewOxm49prynOkZnjXjw&secretKey=SnVpPOO1eWkQuIEGaIARTR4DzmIMOadvHW7iIHHbB1XPwhMV

  rekoni:
    image: hardcoreeng/rekoni-service:v0.6.501
    environment:
      - SECRET=8fd5232fc27805cf4899d27789521345e7b2dca04dab315c06fbf73c1a0be031e96c786a52d83222419d02686f53ea8686dd4fa484087544a832855f57e769ed
      - PORT=4004

  stats:
    image: hardcoreeng/stats:v0.6.501
    environment:
      - PORT=4900
      - SERVER_SECRET=8fd5232fc27805cf4899d27789521345e7b2dca04dab315c06fbf73c1a0be031e96c786a52d83222419d02686f53ea8686dd4fa484087544a832855f57e769ed

  mongodb:
    image: "mongo:7-jammy"
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=B26ppVvQYhB3MtxrDR040JzidriNbc5J
    volumes:
      - db:/data/db
    restart: unless-stopped

  minio:
    image: "minio/minio"
    command: server /data --address ":9000" --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=ndFN1zncIp0QQewOxm49prynOkZnjXjw
      - MINIO_ROOT_PASSWORD=SnVpPOO1eWkQuIEGaIARTR4DzmIMOadvHW7iIHHbB1XPwhMV
    volumes:
      - files:/data
    restart: unless-stopped

  elastic:
    image: "elasticsearch:7.14.2"
    command: |
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment || yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - elastic:/usr/share/elasticsearch/data
    environment:
      - ELASTICSEARCH_PORT_NUMBER=9200
      - BITNAMI_DEBUG=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx1536m
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:8082
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: unless-stopped

volumes:
  db:
  elastic:
  files: